### ISSUE TITLE
Wireguard service in dashboard

### ISSUE THREAD

**Issue by steakhutzeee** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#20]
Hi,

noted that installing this plugin also install the package `6.1.0-0.deb11.11-rt-armmp`. What is the use for it?

Also on my OMV6 even when the service is active i do not see Wireguard under Services in the Dashboard. How could fix this?

Thanks.

**Comment by ryecoaaron** [comment]
> noted that installing this plugin also install the package 6.1.0-0.deb11.11-rt-armmp. What is the use for it?

That looks like a kernel package but you omitted the package name.  The plugin only installs the wireguard and qrencode packages.  It is possible that your system depends on another package to provide the kernel module.

> Also on my OMV6 even when the service is active i do not see Wireguard under Services in the Dashboard. How could fix this?

You can't fix it.  Since wireguard uses a "service" for every tunnel, it is difficult to add that to the Services list on the dashboard.  I could add one service if at least one wireguard service was running but this could be very inaccurate.  So, I chose to not add it.

**Comment by steakhutzeee** [comment]
Thank you.

So actually it's not intended for the plugin to appear under Services, ok. That's strange because there is an user saying he can see it there (link below).

For the kernel package here https://forum.openmediavault.org/index.php?thread%2F49720-wireguard-not-working-module-wireguard-not-found%2F=#post367703 in this post on the forum i pointed out the whole setup i performed. 

The setup of `6.1.0-0.deb11.11-rt-armmp` was directly inside the popup that appears while installing the Wireguard plugin.

**Comment by ryecoaaron** [comment]
> For the kernel package here https://forum.openmediavault.org/index.php?thread%2F49720-wireguard-not-working-module-wireguard-not-found%2F=#post367703 in this post on the forum i pointed out the whole setup i performed.

I just posted on that thread.  You had to install wireguard-dkms because the old 5.4 kernel on your 32bit odroid doesn't have the wireguard module.

> The setup of 6.1.0-0.deb11.11-rt-armmp was directly inside the popup that appears while installing the Wireguard plugin.

That is due to the apt commands that OMV uses to install plugins.  It is apt resolving dependencies not the plugin.  https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/pluginmgmt.inc#L238
